---
- name: create an environnement
  hosts: ansible_client
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
#vars project
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "ansibletest-project1"
    OS_DNS_NAMESERVER1: "8.8.8.8"
#vars user
    USERMEMBER: "nadia"
    PASSWORD_USER: "root"
    EMAIL_USER: "nadia@gmail.com"
#vars image
    NAME_IMAGE: "centos7"
    FILENAME: "/home/admin/Téléchargements/CentOS-7-x86_64-DVD-2009.iso"
    DISK_FORMAT: "iso"
    DISTRO: "centos"
#vars externe network
    NAME_EXT_NETWORK: "externe_network"
#vars externe subnet
    NAME_EXT_SUBNET: "externe_subnet"
    CIDR_SUBNET: "192.168.0.0/24"
    DNS_NAMESERVERS: "8.8.8.8"
    ALLOCATION_POOL_START: "192.168.0.10"
    ALLOCATION_POOL_END: "192.168.0.20"
#vars interne network
    NAME_INT_NETWORK: "int_network"
#vars interne subnet
    NAME_INT_SUBNET: "int_subnet"
    CIDR_INT_SUBNET: "10.0.16.0/24"
#vars router
    NAME_ROUTER: "router2"
#vars security_group
    SECURITY_GROUP: "groupe1"
    PROTOCOL: "icmp"
  tasks:
    - debug: var=ansible_host
    - name: Create a project
      os_project:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        region_name: RegionOne
        domain_id: default
        name: "{{ OS_PROJECT }}"
    - name: Create user
      os_user:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ USERMEMBER }}"
        password: "{{ PASSWORD_USER }}"
        email: "{{ EMAIL_USER }}"
        domain: default
        default_project: "{{ OS_PROJECT }}"

    - name: Attach user to project
      os_user_role:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        role: _member_
        region_name: RegionOne
        project: "{{ OS_PROJECT }}"
        user: "{{ USERMEMBER }}"
    - name: create an image
      os_image:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_IMAGE }}"
        container_format: bare
        disk_format: "{{ DISK_FORMAT }}"
        filename: "{{ FILENAME }}"
        properties:
          cpu_arch: x86_64
          distro: "{{ DISTRO }}"
    - name : create an externe network
      os_network:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_EXT_NETWORK }}"
        external: true
        shared: yes
    - name: create an externe subnet
      os_subnet:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        network_name: "{{ NAME_EXT_NETWORK }}"
        name: "{{ NAME_EXT_SUBNET }}"
        cidr: "{{ CIDR_SUBNET }}"
        enable_dhcp: yes
        allocation_pool_start: "{{ ALLOCATION_POOL_START }}"
        allocation_pool_end: "{{ ALLOCATION_POOL_END }}"
        dns_nameservers: "{{ DNS_NAMESERVERS }}"
    - name : create an interne  network
      os_network:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_INT_NETWORK }}"
        project: "{{ OS_PROJECT }}"
    - name: create an interne subnet
      os_subnet:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        network_name: "{{ NAME_INT_NETWORK }}"
        name: "{{ NAME_INT_SUBNET }}"
        cidr: "{{ CIDR_INT_SUBNET }}"
        dns_nameservers: "{{ DNS_NAMESERVERS }}"
        project: "{{ OS_PROJECT }}"

#    - name: create a router
#      os_router:
#        state: present
#        auth:
#          auth_url: "{{ OS_AUTH_URL }}"
#          username: "{{ OS_USERNAME }}"
#
#          password: "{{ OS_PASSWORD }}"
#          project_name: "{{ OS_PROJECT_NAME }}"
#          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
#          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
#        name: "{{ NAME_ROUTER }}"
#        network: "{{ NAME_EXT_NETWORK }}"
#        external_fixed_ips:
#          - subnet: "{{ NAME_EXT_SUBNET }}"
#        interfaces:
#          - "{{ NAME_INT_SUBNET }}"
#        enable_snat: yes
#        project: "{{ OS_PROJECT }}"

    - name: Create a security group
      os_security_group:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ SECURITY_GROUP }}"
        project: "{{ OS_PROJECT }}"

    - name: Create a security group rule
      os_security_group_rule:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        security_group: "{{ SECURITY_GROUP }}"
        protocol: "{{ PROTOCOL }}"
        remote_ip_prefix: 0.0.0.0/0
        project: "{{ OS_PROJECT }}"


...
