---
- name: create a flavor
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "safa"
#vars flavor
    NAME_FLAVOR: "flavor2"
    RAM_FLAVOR: "6000"
    VCPU_FLAVOR: "2"
    DISQUE_FLAVOR: "10"
    DISQUE_EPHEMERAL: "10"

 
  tasks:
    - debug: var=ansible_host
    - name: create a flavor
      os_nova_flavor:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT_NAME }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ NAME_FLAVOR }}"
       ram: "{{ RAM_FLAVOR }}"
       vcpus: "{{ VCPU_FLAVOR }}"
       disk: "{{ DISQUE_FLAVOR }}"
       ephemeral: "{{ DISQUE_EPHEMERAL }}"
    
