---
- name: create IP FLOATING
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "clientabcd"
    OS_PASSWORD: "root"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "ABCD"
    OS_PROJECT: "ABCD"
#vars ip floating 
    NAME_INSTANCE: "instance ABCD"
    NAME_EXT_NETWORK: "ABCD_ext_net"
  tasks:
    - name: create a floating_ip
      os_floating_ip:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT_NAME }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       reuse: yes
       server: "{{ NAME_INSTANCE }}"
       network: "{{ NAME_EXT_NETWORK }}"
    
