---
- name: create project
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
 
#vars image
    NAME_IMAGE: "centos7"
    FILENAME: "/home/admin/Téléchargements/CentOS-7-x86_64-DVD-2009.iso"
    DISK_FORMAT: "iso"
    DISTRO: "centos"    
  tasks:
    - debug: var=ansible_host
    - name: create an image
      os_image:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_IMAGE }}"
        container_format: bare
        disk_format: "{{ DISK_FORMAT }}"
        filename: "{{ FILENAME }}"
        properties:
          cpu_arch: x86_64
          distro: "{{ DISTRO }}"    
