---
- name: create an instance 
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
#vars instance
    NAME_INSTANCE: "{{ name | default(None) }}"
    NAME_INT_NETWORK: "{{ int_network| default(None) }}"
#    NAME_IMAGE: "centos7"
    NAME_IMAGE: "cirross"
    SECURITY_GROUP: "{{ sec_grp | default(None) }}"
    KEY_NAME: "{{ key | default(None) }}"
    NAME_FLAVOR: "m1.tiny"
  tasks:

    - name: create a new instance
      os_server:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ NAME_INSTANCE }}"
       image: "{{ NAME_IMAGE }}"
       key_name: "{{ KEY_NAME }}"
       flavor: "{{ NAME_FLAVOR }}"
       network: "{{ NAME_INT_NETWORK }}"
       security_groups: "{{ SECURITY_GROUP }}"
       auto_ip: yes
       region_name: RegionOne
       wait: false
       



   

    
