---
- name: create project
  hosts: all
  remote_user: root
  vars_prompt:
    - name: OS_PROJECT
      prompt: Entrer le nom du projet
      private: no
  vars:
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
    OS_DNS_NAMESERVER1: "8.8.8.8"
#    OS_PROJECT: "safa"    
  tasks:
    - debug: var=ansible_host
    - name: Create a project
      os_project:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"

        region_name: RegionOne
        domain_id: default
        name: "{{ OS_PROJECT }}"
...

