---
- name: define a quotas
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
#vars quota
    INSTANCES_PROJECT: "{{ instances | default(None) }}"
    CORES_PROJECT: "{{ cores | default(None) }}"
    RAM_PROJECT: "{{ ram | default(None) }}"
    VOLUMES_PROJECT: "{{ volumes | default(None) }}"
    SNAPSHOTS_PROJECT: "{{ snapshot | default(None) }}"
    SECURITY_GROUP_PROJECT: "{{ security_group | default(None) }}"
    NETWORK_PROJECT: "{{ network | default(None) }}"
    SUBNET_PROJECT: "50"
    GIGABYTES_PROJECT: "500"


  tasks:
    - name: set a project quotas
      os_quota:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT_NAME }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ OS_PROJECT }}"
       instances: "{{ INSTANCES_PROJECT }}"
       cores: "{{ CORES_PROJECT }}"
       ram: "{{ RAM_PROJECT }}"
       volumes: "{{ VOLUMES_PROJECT }}"
       snapshots: "{{ SNAPSHOTS_PROJECT }}"
       security_group: "{{ SECURITY_GROUP_PROJECT }}"
       network: "{{ NETWORK_PROJECT }}"
       subnet: "{{ SUBNET_PROJECT }}"
       gigabytes: "{{ GIGABYTES_PROJECT }}"    
