
---
- name: create a volume 
  hosts: all
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "{{ member | default(None) }}"
    OS_PASSWORD: "{{ password | default(None) }}"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
#vars project
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
    OS_DNS_NAMESERVER1: "8.8.8.8"
    NAME_INSTANCE: "{{ name | default(None) }}"
#vars volume
    NAME_VOLUME: "{{ volume | default(None) }}"
    SIZE_VOLUME: "{{ size | default(None) }}"
  tasks:

    - name : create a volume
      os_volume:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        display_name: "{{ NAME_VOLUME }}"
        size: "{{ SIZE_VOLUME }}"
        server: "{{ name }}"

